apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
        - name: tomcat-app
          image: rajf5/tomcat-app-pipeline:1.0.0-7
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
