apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-service
  labels:
    app: tomcat-app 
spec:
  selector:
    app: tomcat-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
